name: lucis
description: A social location sharing app


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  image_picker: ^0.8.4+9
  path_provider: ^2.0.9
  path: ^1.8.0
  sqflite: ^2.0.2
  location: ^4.3.0
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  geoflutterfire: ^3.0.3
  infinite_scroll_pagination: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  assets:
    - assets/images/


